### ISSUE TITLE
Switching from any dunegon to Lower Kara throws error and keeps mob count

### ISSUE THREAD

**Issue by Havoh** [nnogga/MethodDungeonTools#34]
When I switched from any dungeon to Lower Kara it throws an error (linked below) and also keeps the mob count I did from the dungeon on the side.

BugSack: [Link](https://pastebin.com/0YUeKqxF)
Example: [Streamable](https://streamable.com/vlm9d)

**Comment by Xyxeii** [comment]
I can't confirm, but this error might be leftover from a bug I reported #27. This has since been fixed, however if you have a bugged pull in your saved variables, the issue might remain. 

To confirm this, you could remove your MDT saved variables file as well as the .bak. _I suggest moving the files to a different location rather then deleting them in case this doesn't work; then you can always put them back._ After removing the files, reload the game so that a new file can be created in it's place. Then try and replicate the bug.

**Comment by nnogga** [comment]
Can @Havoh confirm if resetting savedvariables resolves the issue? If yes then i will consider this issue fixed and won't spend time on modernizing old presets.

**Comment by Havoh** [comment]
Just tested it and it seems to be working again when I removed them.
